;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2017/8/30 15:53:08

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1000=术语解释.txt	; 术语解释
